import {useEffect,useMemo,useRef,useState} from 'react';
import {api,connect} from './api';
import type {Reading,Station} from './types';
import {AirMap,type MappedStation,type MapPick,type SchoolPOI} from './components/AirMap';
type Filter='all'|'corridor';

export function App(){
  const dataPage=location.pathname.replace(/\/+$/,'').endsWith('/data');
  const[stations,setStations]=useState<Station[]>([]),[readings,setReadings]=useState<Record<string,Reading>>({});
  const[error,setError]=useState(false),[retry,setRetry]=useState(0),[selection,setSelection]=useState<MapPick|undefined>(undefined),[filter,setFilter]=useState<Filter>('all'),[windowMode,setWindowMode]=useState<'24h'|'7d'|'30d'>('7d');
  const[userLocation,setUserLocation]=useState<[number,number]|undefined>(undefined),[locationState,setLocationState]=useState<'idle'|'asking'|'found'|'denied'>('idle');
  useEffect(()=>{let alive=true;api.stations().then(s=>{if(alive){setStations(s);setError(false)}}).catch(()=>alive&&setError(true));api.latest().then(r=>alive&&setReadings(Object.fromEntries(r.map(x=>[x.station_id,x])))).catch(()=>{});const disconnect=connect(r=>setReadings(v=>({...v,[r.station_id]:r})));return()=>{alive=false;disconnect()}},[retry]);
  const mapped=useMemo<MappedStation[]>(()=>stations.map(s=>({...s,pm:readings[s.id]?.measurements.pm2_5.value,aqi:readings[s.id]?.indices.sl_aqi.value,windSpeed:readings[s.id]?.meteorology?.wind_speed_ms??undefined,windDirection:readings[s.id]?.meteorology?.wind_direction_deg??undefined})),[stations,readings]);
  const visible=useMemo(()=>mapped.filter(s=>filter==='all'||s.site_class==='TRAFFIC_CORRIDOR'),[mapped,filter]);
  const locate=()=>{if(!navigator.geolocation){setLocationState('denied');return}setLocationState('asking');navigator.geolocation.getCurrentPosition(p=>{const point:[number,number]=[p.coords.longitude,p.coords.latitude];setUserLocation(point);setLocationState('found');const nearest=nearestStation(point,mapped);if(nearest)setSelection({kind:'station',id:nearest.id})},()=>setLocationState('denied'),{enableHighAccuracy:true,timeout:12000,maximumAge:300000})};
  const asked=useRef(false);useEffect(()=>{if(stations.length&&!asked.current){asked.current=true;locate()}},[stations.length]);
  return <div className="shell map-shell"><Nav dataActive={dataPage}/><main className="map-main">{dataPage?<DataPage stations={stations} readings={readings}/>:<MapHome stations={visible} allStations={mapped} readings={readings} selection={selection} onSelect={setSelection} filter={filter} setFilter={setFilter} windowMode={windowMode} setWindowMode={setWindowMode} userLocation={userLocation} locationState={locationState} locate={locate} error={error} retry={()=>setRetry(v=>v+1)}/>}</main></div>
}

function Nav({dataActive}:{dataActive:boolean}){return <aside className="rail map-rail" aria-label="Primary"><a className="mark" href="/app/" aria-label="aqi.thingsnode home">a.</a><a className={!dataActive?'active':''} href="/app/"><span className="nav-icon">⌖</span><span>Map</span></a><a className={dataActive?'active':''} href="/app/data"><span className="nav-icon">↓</span><span>Data</span></a></aside>}

function MapHome(props:{stations:MappedStation[];allStations:MappedStation[];readings:Record<string,Reading>;selection?:MapPick;onSelect:(p:MapPick|undefined)=>void;filter:Filter;setFilter:(f:Filter)=>void;windowMode:'24h'|'7d'|'30d';setWindowMode:(w:'24h'|'7d'|'30d')=>void;userLocation?:[number,number];locationState:string;locate:()=>void;error:boolean;retry:()=>void}){
  const[query,setQuery]=useState(''),[legend,setLegend]=useState(true);
  const matches=query.trim()?props.allStations.filter(s=>`${s.name} ${s.corridor??''} ${s.district}`.toLowerCase().includes(query.toLowerCase())).slice(0,5):[];
  const selectedStation=props.selection?.kind==='station'?props.allStations.find(s=>s.id===props.selection!.id):undefined;
  const selectedSchool=props.selection?.kind==='school'?props.selection:undefined;
  return <section className="map-home"><AirMap stations={props.stations} selected={props.selection} onSelect={props.onSelect} userLocation={props.userLocation} windowMode={props.windowMode}/>
    <div className="map-brand"><span>aqi.</span>thingsnode</div>
    <div className="map-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Corridor, district or station" aria-label="Search stations"/>{matches.length>0&&<div className="search-results">{matches.map(s=><button key={s.id} onClick={()=>{props.onSelect({kind:'station',id:s.id});setQuery('')}}>{s.name}<small>{s.district} · {s.site_class.replaceAll('_',' ')}</small></button>)}</div>}<div className="map-filters"><button className={props.filter==='all'?'on':''} onClick={()=>props.setFilter('all')}>All stations</button><button className={props.filter==='corridor'?'on':''} onClick={()=>props.setFilter('corridor')}>Traffic corridors</button></div></div>
    <div className="map-top-controls"><span className="demo-pill"><i/>Demo data</span><div className="segmented">{(['24h','7d','30d'] as const).map(w=><button key={w} className={props.windowMode===w?'on':''} onClick={()=>props.setWindowMode(w)}>{w}</button>)}</div></div>
    <button className={`locate-button ${props.locationState}`} onClick={props.locate} title="Use my location" aria-label="Use my location">{props.locationState==='asking'?'…':'◎'}</button>
    {props.error&&<div className="map-error"><b>Application API unavailable</b><button onClick={props.retry}>Retry</button></div>}
    <Legend open={legend} toggle={()=>setLegend(v=>!v)} mode={props.windowMode}/>
    {(selectedStation||selectedSchool)&&<DetailSheet station={selectedStation} school={selectedSchool} reading={selectedStation?props.readings[selectedStation.id]:undefined} allStations={props.allStations} readings={props.readings} windowMode={props.windowMode} close={()=>props.onSelect(undefined)}/>} 
  </section>
}

function DetailSheet({station,school,reading,allStations,readings,windowMode,close}:{station?:MappedStation;school?:SchoolPOI;reading?:Reading;allStations:MappedStation[];readings:Record<string,Reading>;windowMode:string;close:()=>void}){
  const isSchool=!!school||station?.site_class==='SCHOOL';const schoolPoint=school??(station?{id:station.id,name:station.name,lng:station.lng,lat:station.lat,category:'school' as const}:undefined);const sensor=schoolPoint?(station?.site_class==='SCHOOL'?station:nearestStation([schoolPoint.lng,schoolPoint.lat],allStations.filter(s=>s.site_class!=='SCHOOL'))):station;const sensorReading=sensor?readings[sensor.id]:reading;const pm=sensorReading?.measurements.pm2_5.value;const[expanded,setExpanded]=useState(true);const dragStart=useRef<number|undefined>(undefined);const educationLabel=schoolPoint?.category==='university'?'University view':'School view';
  const pointerDown=(e:React.PointerEvent)=>{dragStart.current=e.clientY;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};const pointerUp=(e:React.PointerEvent)=>{if(dragStart.current!==undefined){const delta=e.clientY-dragStart.current;if(Math.abs(delta)>35)setExpanded(delta<0);dragStart.current=undefined}};
  return <aside className={`selection-sheet ${expanded?'expanded':'collapsed'}`} aria-label={isSchool?'Education location details':'Station details'}><button className="sheet-handle" onPointerDown={pointerDown} onPointerUp={pointerUp} onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'Collapse details':'Expand details'}><i/></button><div className="sheet-head"><div><div className="eyebrow">{isSchool?educationLabel:station?.name}</div><h2>{isSchool?schoolPoint?.name:station?.name}</h2><small>{sensor?`Nearest sensor · ${sensor.name}`:'No sensor available'}</small></div><button className="sheet-close" onClick={close} aria-label="Close">×</button></div><div className="sheet-scroll">{isSchool?<SchoolSummary pm={pm} reading={sensorReading}/>:<StationSummary station={station!} reading={reading} windowMode={windowMode}/>}</div><div className="sheet-actions"><a className="primary-action" href={`/api/v1/export?stations=${sensor?.id??''}&format=csv`} download>Download readings</a><a href={`/api/v1/export?stations=${sensor?.id??''}&format=json`} download>Download JSON</a></div></aside>
}

function StationSummary({station,reading,windowMode}:{station:MappedStation;reading?:Reading;windowMode:string}){const pm=reading?.measurements.pm2_5.value,aqi=reading?.indices.sl_aqi;return <><TwinCompact aqi={aqi?.value} band={aqi?.band} pm={pm}/><div className="exposure"><div><span>Exposure over {windowMode}</span><b>{pm?`${(pm/15).toFixed(1)}× WHO`:'—'}</b></div><SegmentedAqiBar pm={pm} className="exposure-track"/><small>Marker is the WHO 24-hour level for this window</small></div><div className="provenance"><div className="eyebrow">Provenance</div><p><span>Source</span><b>{reading?.provenance.source_type??'Awaiting telemetry'}</b></p><p><span>Calibration</span><b>{reading?.provenance.calibration_state??'—'}</b></p><p><span>Confidence</span><b>{reading?.provenance.confidence??'—'}</b></p></div><p className="coordinates numeric">{station.lat.toFixed(4)}, {station.lng.toFixed(4)} · {station.site_class.replaceAll('_',' ')}</p></>}
function SchoolSummary({pm,reading}:{pm?:number;reading?:Reading}){const state=pm===undefined?'Waiting for live air data':pm<30?'Outdoor activity as scheduled.':pm<55?'Limit outdoor activity.':'Move activities indoors.';return <><div className="school-advisory"><div className="eyebrow">Today’s advisory</div><h3>{state}</h3><p>{pm===undefined?'No value is substituted while the nearest sensor is unavailable.':pm<30?'The nearest station is below the published action threshold. Keep checking around arrival and departure.':pm<55?'Keep sessions short and avoid the morning and afternoon traffic peaks.':'Use indoor spaces for PE and breaks until readings fall.'}</p>{pm!==undefined&&<div className="why-line">Nearest-station PM2.5 <b>{pm.toFixed(1)} µg/m³</b> · {(pm/15).toFixed(1)}× WHO guideline</div>}</div><TwinCompact aqi={reading?.indices.sl_aqi.value} band={reading?.indices.sl_aqi.band} pm={pm}/><div className="school-window"><div className="eyebrow">Nearest reading now</div><SegmentedAqiBar pm={pm} className="school-now-scale"/><small>The marker is the WHO guideline. A school-day pattern will appear after enough hourly readings accumulate.</small></div></>}
function SegmentedAqiBar({pm,className}:{pm?:number;className:string}){const count=40,active=Math.round(Math.min(1,Math.max(0,(pm??0)/60))*count);const tickClass=(index:number)=>{const position=index/count;return position<.22?'tick-good':position<.38?'tick-moderate':position<.55?'tick-slightly':position<.72?'tick-unhealthy':position<.88?'tick-very':'tick-hazardous'};return <div className={`segmented-aqi-bar ${className}`} role="img" aria-label={pm===undefined?'Air quality reading unavailable':`PM2.5 ${pm.toFixed(1)} micrograms per cubic metre`}>
  {Array.from({length:count},(_,index)=><span key={index} className={index<active?tickClass(index):''}/>)}<em/>
</div>}
function TwinCompact({aqi,band,pm}:{aqi?:number;band?:string;pm?:number}){return <div className="twin-compact"><div><span>Sri Lanka<br/>AQI</span><strong className="numeric">{aqi??'—'}</strong><b>{band??'Awaiting'}</b></div><div><span>WHO<br/>24-hour</span><strong className="who-small">{pm===undefined?'Awaiting':pm>15?'Above guideline':'Within guideline'}</strong><b className="numeric">{pm?.toFixed(1)??'—'} µg/m³</b></div></div>}
function Legend({open,toggle,mode}:{open:boolean;toggle:()=>void;mode:string}){const bands=[['Good','0–50','good'],['Moderate','51–100','moderate'],['Slightly Unhealthy','101–150','slightly'],['Unhealthy','151–200','unhealthy'],['Very Unhealthy','201–300','very'],['Hazardous','301–500','hazardous']];return <div className={`map-legend ${open?'open':''}`}><button onClick={toggle}><b>Sri Lanka AQI</b><span>{open?'▾':'▴'}</span></button>{open&&<div>{bands.map(([name,range,key])=><p key={key}><i className={key}/><b>{name}</b><span>{range}</span></p>)}<small>Field shows {mode==='24h'?'current air':mode==='7d'?'7-day exposure':'the 30-day pattern'} around each station.</small></div>}</div>}

function DataPage({stations,readings}:{stations:Station[];readings:Record<string,Reading>}){return <section className="page-content data-page"><a className="back" href="/app/">← Return to map</a><div className="intro"><p className="eyebrow">Open by default</p><h2>Methods, readings and provenance</h2><p>Every reading retains its raw values, correction state, source and confidence.</p></div><div className="cards data-grid"><article><div className="eyebrow">REST API</div><h3>{stations.length} stations · {Object.keys(readings).length} live readings</h3><a href="/api/v1/docs">Open API documentation →</a></article><article><div className="eyebrow">All readings</div><h3>Download the current dataset</h3><a href="/api/v1/export?format=csv" download>Download CSV →</a></article><article><div className="eyebrow">Methodology</div><h3>Known limits are part of the data</h3><a href="https://github.com/ThingNode/aqi-tn/tree/main/docs/methodology">Read methodology →</a></article></div></section>}
function nearestStation(point:[number,number],stations:MappedStation[]){return stations.reduce<MappedStation|undefined>((best,s)=>!best||distance(point,[s.lng,s.lat])<distance(point,[best.lng,best.lat])?s:best,undefined)}
function distance(a:[number,number],b:[number,number]){const r=Math.PI/180,dLat=(b[1]-a[1])*r,dLng=(b[0]-a[0])*r,x=Math.sin(dLat/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
